import { Inter } from "next/font/google";
import "./globals.css";
import clsx from "clsx";
import FireFliesBackground from "@/components/FireFliesBackground";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter"
});

export const metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={inter.variable}>
      <body className={clsx('font-[var(--font-inter)]', 'bg-[var(--color-background)]', 'text-[var(--color-foreground)]')}>{children}
        <FireFliesBackground />
      </body>
    </html>
  );
}
